### ISSUE TITLE
Do you know how to use REST API of custom voice?

### ISSUE THREAD

**Issue by sannnyu** [boltomli/Data-for-CustomVoice.AI#1]
The offical website of custom voice does not describe it specific, especially in how to call REST API in my app. I really have no idea why this problem occurred.

Here is my operate steps ， if you can not read Chinese Pls contact me！ I will send an English email  to you.

[https://www.cnblogs.com/-SANG/p/9412090.html](https://www.cnblogs.com/-SANG/p/9412090.html)

( if you have some videoes about how to call custom voice api could be better.)

And last thx for your great help !

**Comment by boltomli** [comment]
Hi Li, it's really amazing to see you finished all the steps and got a working model! For the REST API call, it should be similar to [cognitive service sample](https://github.com/Azure-Samples/Cognitive-Speech-TTS/blob/master/Samples-Http/Python/TTSSample.py). I didn't find any obvious issue in the POST. Let me check if there's any upgrade on the custom voice site and consult experts. (BTW, yes, we speak Chinese)

**Comment by sannnyu** [comment]
Yes ,the doc says it's same as Speech,  I also tried many times and failed.  Google shows no such kind of issues.

**Comment by xiaozhouz** [comment]
In your case seems you cannot connect to the speak endpoint server. 

Can you open https://westus.voice.speech.microsoft.com/cognitiveservices? It should show some error message like below if you can connect to the endpoint server:
"<h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p>Ref A: D780B5F9A60D4876A8DB8E76ACA767E1 Ref B: TYO01EDGE1421 Ref C: 2018-09-03T03:58:28Z"

**Comment by xiaozhouz** [comment]
Please try below sample code and ssml:
[ssml_customer.txt](https://github.com/boltomli/Data-for-CustomVoice.AI/files/2344240/ssml_customer.txt)

            WebRequest webRequest = WebRequest.Create(url);            
            webRequest.ContentType = "application/ssml+xml";
            webRequest.Headers.Add("X-MICROSOFT-OutputFormat", "riff-16khz-16bit-mono-pcm");
            webRequest.Headers["Authorization"] = "Bearer " + tokenString;
            webRequest.Timeout = 6000000;
            webRequest.Method = "POST";

            StreamReader sr = new StreamReader(@"D:\testcode\ssml_customer.txt");
            string ssml = sr.ReadToEnd();

            byte[] btBodys = Encoding.UTF8.GetBytes(ssml);
            webRequest.ContentLength = btBodys.Length;
            webRequest.GetRequestStream().Write(btBodys, 0, btBodys.Length);
            
            WebResponse httpWebResponse = null;
            try
            {
                httpWebResponse = webRequest.GetResponse();
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
                return;
            }

**Comment by sannnyu** [comment]
Yes, it works !  Thx for your help !  @boltomli  @xiaozhouz 

I find some points we should notice

![image](https://user-images.githubusercontent.com/16554316/44992081-cba97300-afc8-11e8-9892-e38954de2810.png)

here should be written VoiceModel name, not voice data or sth else which is a key point

![image](https://user-images.githubusercontent.com/16554316/44992184-1e832a80-afc9-11e8-892a-ce749c3f178d.png)

and another point is X-Microsoft-OutputFormat

![image](https://user-images.githubusercontent.com/16554316/44992242-483c5180-afc9-11e8-84aa-f1252aafdecd.png)

after press SEND button you could see the status code is "OK" or "200"

if you wanna hear your bot voice, you could download the ResponseStream

![image](https://user-images.githubusercontent.com/16554316/44992454-d6b0d300-afc9-11e8-8f02-9e27e5ac2b95.png)


At last , really appreciate your guys !
